Adds details to testing to show there is a utf-16 lossiness.
The test output change shows this as an example failure (formatted
for readability here):

Caused by: org.junit.ComparisonFailure: Collection Names not equal.
  UTF-8 hex [
    e197b6eca7bfcead3fe397a8e8a498e5bab4ee8b99ec9e8b
    e197b6eca7bfcead3fe397a8e8a498e5bab4ee8b99ec9e8b
  ] (equals)
  UTF-16 hex [
    feff15f6c9ff03adfffd35e889185eb4e2d9c78b
    feff15f6c9ff03ad003f35e889185eb4e2d9c78b
  ] (NOT equal)
  expected:<á—¶ì§¿Î­[?]ã—¨è¤˜åº´î‹™ìž‹> but was:<á—¶ì§¿Î­[?]ã—¨è¤˜åº´î‹™ìž‹>

If collection names are created an have utf-16 bytes they will be
narrowed to utf-8, so doing something like:
String myFancyStringLocal = [string with utf-16 chars]
String stringFromOio = putDataWithCollectionName(myFancyStringLocal).getCollectionName();
myFancyStringLocal.equals(stringFromOio); // <-- Fails
This happens when the process of narrowing a utf-16 string down to utf-8 and then
widening the utf-8 BACK up to utf-8 is lossy.

I may be interptreting this incorrectly, but I think the reasonable thing here is that
since json only supports utf-8, we only support strings that fit into utf8
without loss?  Basically, can we get the fuzz tester to either never generate strings
in the 16 space that are lossy during conversion cycle OR we start the test method by
normalizing it with something funky like:
String utf8Coll = new String(coll.getBytes(Charset.forName("UTF-8")), Charset.forName("UTF-8"))